services:
  - type: web
    name: lms-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python seed_data.py && python manage.py collectstatic --noinput
    startCommand: gunicorn lms.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lms.settings
