services:
  - type: web
    name: lms-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn lms.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lms.settings
