# Generated by Django 6.0 on 2025-12-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('MENTOR', 'Mentor'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10),
        ),
    ]
